/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as CanchaRouteImport } from './routes/cancha'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as SeguridadRouteImport } from './routes/seguridad'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as TiendasRouteImport } from './routes/tiendas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const CanchaRoute = CanchaRouteImport.update({
  id: '/cancha',
  path: '/cancha',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const SeguridadRoute = SeguridadRouteImport.update({
  id: '/seguridad',
  path: '/seguridad',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendasRoute = TiendasRouteImport.update({
  id: '/tiendas',
  path: '/tiendas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cancha': typeof CanchaRoute
  '/chat': typeof ChatRoute
  '/equipo': typeof EquipoRoute
  '/privacidad': typeof PrivacidadRoute
  '/seguridad': typeof SeguridadRoute
  '/stats': typeof StatsRoute
  '/tiendas': typeof TiendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cancha': typeof CanchaRoute
  '/chat': typeof ChatRoute
  '/equipo': typeof EquipoRoute
  '/privacidad': typeof PrivacidadRoute
  '/seguridad': typeof SeguridadRoute
  '/stats': typeof StatsRoute
  '/tiendas': typeof TiendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cancha': typeof CanchaRoute
  '/chat': typeof ChatRoute
  '/equipo': typeof EquipoRoute
  '/privacidad': typeof PrivacidadRoute
  '/seguridad': typeof SeguridadRoute
  '/stats': typeof StatsRoute
  '/tiendas': typeof TiendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/cancha'
    | '/chat'
    | '/equipo'
    | '/privacidad'
    | '/seguridad'
    | '/stats'
    | '/tiendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/cancha'
    | '/chat'
    | '/equipo'
    | '/privacidad'
    | '/seguridad'
    | '/stats'
    | '/tiendas'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/cancha'
    | '/chat'
    | '/equipo'
    | '/privacidad'
    | '/seguridad'
    | '/stats'
    | '/tiendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  CanchaRoute: typeof CanchaRoute
  ChatRoute: typeof ChatRoute
  EquipoRoute: typeof EquipoRoute
  PrivacidadRoute: typeof PrivacidadRoute
  SeguridadRoute: typeof SeguridadRoute
  StatsRoute: typeof StatsRoute
  TiendasRoute: typeof TiendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancha': {
      id: '/cancha'
      path: '/cancha'
      fullPath: '/cancha'
      preLoaderRoute: typeof CanchaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguridad': {
      id: '/seguridad'
      path: '/seguridad'
      fullPath: '/seguridad'
      preLoaderRoute: typeof SeguridadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiendas': {
      id: '/tiendas'
      path: '/tiendas'
      fullPath: '/tiendas'
      preLoaderRoute: typeof TiendasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  CanchaRoute: CanchaRoute,
  ChatRoute: ChatRoute,
  EquipoRoute: EquipoRoute,
  PrivacidadRoute: PrivacidadRoute,
  SeguridadRoute: SeguridadRoute,
  StatsRoute: StatsRoute,
  TiendasRoute: TiendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
